# Generated by Django 2.2.7 on 2019-12-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipdail', '0006_auto_20191216_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
